In [1]:
#Dot Product with Python

A = [2,6,5]
B = [7,4,6]

dot = sum([ A[i] * B[i] for i in range(len(A))])

print(dot)



68


In [2]:
# Dot Product with Pythonic Way

A = [2,6,5]
B = [7,4,6]

dot = sum(a * b for a, b in zip(A, B))

print(dot)


68


In [3]:
# Dot product with Numpy

import numpy as np

A = np.array([2, 6, 5])
B = np.array([7, 4, 6])

dot = np.dot(A, B)

print(dot)

68


In [4]:
# Magnitude of Vector

import math

A = [2,6,5]

magnitude = math.sqrt(sum(x*x for x in A))

print(magnitude)

8.06225774829855


In [5]:
# Magnitude of Vector using Numpy

import numpy as np
A = [2,6,5]

magnitude = np.linalg.norm(A)

print(magnitude)

8.06225774829855


In [6]:
#Cosine Similarlirty using Python

import math

A = [2,6,5]
B = [7,4,6]

dot = sum(a * b for a, b in zip(A,B))

mag_A = math.sqrt(sum(a * a for a in A))
mag_B = math.sqrt(sum(b * b for b in B))

cosisimilarity = dot / (mag_A * mag_B)

print(cosisimilarity)

0.8392503817997966


In [7]:
#Cosine Similarlirty using Numpy

import numpy as np

A = np.array([2,6,5])
B = np.array([7,4,6])

dot = np.dot(A, B)

mag_A = np.linalg.norm(A)
mag_B = np.linalg.norm(B)

cosisimilarity = dot / (mag_A * mag_B)

print(cosisimilarity)

0.8392503817997966


In [8]:
#Eucledian distance with Python

A = [2,6,5]
B = [7,4,6]

diff = [ A[i] - B[i] for i in range(len(A))]

eq_sum = sum( x * x for x in diff )

EuDistance = math.sqrt(eq_sum)

print(EuDistance)


5.477225575051661


In [9]:
#Using Zip

import math

A = [2,6,5]
B = [7,4,6]

sum_sq = 0

for a,b in zip(A,B):
  sum_sq += (a-b) ** 2

distance = math.sqrt(sum_sq)

print(distance)



5.477225575051661


In [10]:
#Using Numpy

A = np.array([2,6,5])
B = np.array([7,4,6])

distance = np.linalg.norm(A - B)
print(distance)


5.477225575051661


In [11]:
#matrix Multiplication using Python

A = [[2,6,5],
     [7,4,6],
     [8,5,4]]

B = [[8,4,5],
     [8,6,6],
     [1,4,3]]

rows = len(A)
cols = len(B[0])
common = len(B)

C = [[0] * cols for _ in range(rows)]

for i in range(rows):
    for j in range(cols):
        for k in range(common):
            C[i][j] += A[i][k] * B[k][j]

for row in C:
    print(row)


[69, 64, 61]
[94, 76, 77]
[108, 78, 82]


In [12]:
#using Numpy

A = [[2,6,5],
     [7,4,6],
     [8,5,4]]

B = [[8,4,5],
     [8,6,6],
     [1,4,3]]

C  = np.matmul(A, B)
print(C)

[[ 69  64  61]
 [ 94  76  77]
 [108  78  82]]


In [13]:
#Transpose

A = [
    [1, 2, 3],
    [4, 5, 6]
]

rows = len(A)
cols = len(A[0])

transpose = []

for j in range(cols):
    row = []
    for i in range(rows):
        row.append(A[i][j])
    transpose.append(row)

for row in transpose:
    print(row)

[1, 4]
[2, 5]
[3, 6]


In [14]:
#Pythonic Way

A = [
    [1, 2, 3],
    [4, 5, 6]
]

transpose = [[A[i][j] for i in range(len(A))]
             for j in range(len(A[0]))]

for row in transpose:
    print(row)

[1, 4]
[2, 5]
[3, 6]


In [15]:
# Using Numpy
A = [
    [8, 2, 3],
    [4, 5, 6]
]

T = np.transpose(A)
print(T)

[[8 4]
 [2 5]
 [3 6]]


In [16]:
#Time : O(m × n)

#Space : O(m × n)

In [24]:
#Determinant using python

def determinant(matrix):
    n = len(matrix)

    # Base case: 1x1
    if n == 1:
        return matrix[0][0]

    # Base case: 2x2
    if n == 2:
        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]

    det = 0

    for col in range(n):
        # Create minor matrix
        minor = []

        for row in matrix[1:]:
            minor.append(row[:col] + row[col+1:])

        sign = (-1) ** col
        det += sign * matrix[0][col] * determinant(minor)

    return det


A = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 2]
]

print(float(determinant(A)))

21.0


In [23]:
#Numpy Implmentation

import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 2]
])

print(np.linalg.det(A))

20.99999999999999


In [25]:
#Python Inverse

import numpy as np

A = np.array([
    [2,3],
    [1,4]
])

inverse = np.linalg.inv(A)

print(inverse)

[[ 0.8 -0.6]
 [-0.2  0.4]]
