In [1]:
import numpy as np
import time

In [18]:
#Test and compare numpy vs python plain code , Vector Addition

# n = 10000000
# a = [1]*n
# b = [2]*n

# start = time.time()
# c = [0]*n

# for i in range(n):
#   c[i] = a[i] + b[i]

# end = time.time()
# print(end - start)

n = 10000000
a = [1] * n
b = [2] * n

start = time.time()

c = [a[i] + b[i] for i in range(n)]

end = time.time()
print(end - start)

0.6680998802185059


In [20]:
start = time.time()
a_np = np.arange(n)
b_np = np.arange(n)

c_np = a_np + b_np
end = time.time()
print(end - start)


0.06942081451416016


In [22]:
0.6680998802185059 / 0.06942081451416016

9.623913013613947

In [24]:
# Create 2 matrices using numpy array

A = np.array([[2,4,5],[8,3,6],[8,4,6]]) #Matrix A
B = np.array([[3,1,2],[4,9,0],[8,4,5]]) #Matrix B





In [25]:
A.shape

(3, 3)

In [26]:
A

array([[2, 4, 5],
       [8, 3, 6],
       [8, 4, 6]])

In [27]:
#Sum Operation

print(A+B)

[[ 5  5  7]
 [12 12  6]
 [16  8 11]]


In [28]:
#dIFFER ENCE Operation

print(A - B)

[[-1  3  3]
 [ 4 -6  6]
 [ 0  0  1]]


In [30]:
#Finding product of the Matrices

#1st Way
print(A@B)

#2nd Way
print(np.matmul(A,B))

[[62 58 29]
 [84 59 46]
 [88 68 46]]
[[62 58 29]
 [84 59 46]
 [88 68 46]]


In [31]:
#Finding transpose of a Matrix
#1St method
print(A.T)

[[2 8 8]
 [4 3 4]
 [5 6 6]]


In [36]:
#2nd Method
print(np.transpose(A))

#Or

print(A.transpose())

[[2 8 8]
 [4 3 4]
 [5 6 6]]
[[2 8 8]
 [4 3 4]
 [5 6 6]]


In [39]:
#Fidning determinant using built in method

print(np.linalg.det(A))
print(np.linalg.det(B))

27.999999999999986
2.9999999999999876


In [41]:
#Fidning Invesrse of a Matrix

print(np.linalg.inv(A))
print(np.linalg.inv(B))


[[-2.14285714e-01 -1.42857143e-01  3.21428571e-01]
 [-1.36642834e-16 -1.00000000e+00  1.00000000e+00]
 [ 2.85714286e-01  8.57142857e-01 -9.28571429e-01]]
[[ 15.           1.          -6.        ]
 [ -6.66666667  -0.33333333   2.66666667]
 [-18.66666667  -1.33333333   7.66666667]]


In [42]:
#Fidning Trace

print(np.linalg.trace(A))
print(np.linalg.trace(B))

11
17


In [43]:
#Rank of a matrix

print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(B))

3
3


In [44]:
#Fidning EigenValue and EigenVector

print(np.linalg.eig(A))
print(np.linalg.eig(B))

EigResult(eigenvalues=array([15.09711721, -3.57889636, -0.51822085]), eigenvectors=array([[-0.43811935, -0.74165341, -0.18531064],
       [-0.61493775,  0.54421286, -0.71970383],
       [-0.65566988,  0.39215122,  0.66909369]]))
EigResult(eigenvalues=array([ 0.0452953 , 10.85084584,  6.10385886]), eigenvectors=array([[ 0.60061788, -0.26954506,  0.35496737],
       [-0.26829154, -0.5825338 , -0.49026254],
       [-0.75317847, -0.76681147,  0.79601558]]))
